spring:
  security:
    saml2:
      relyingparty:
        registration:
          auth0:
            assertingparty:
              metadata-uri: https://dev-ur33izwe4rn2g4cw.us.auth0.com/samlp/metadata/5itQAVHP8Z39lMo9kR20ryXzPDwYhOog
            signing:
              credentials: &signing-credentials
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout: &logout-settings
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
          okta:
            assertingparty:
              metadata-uri: https://dev-88788113.okta.com/app/exkm92izlno28O8rK5d7/sso/saml/metadata
            signing:
              credentials: *signing-credentials
            singlelogout: *logout-settings