spring:
  security:
    saml2:
      relyingparty:
        registration:
          auth0:
            assertingparty:
              metadata-uri: https://dev-06bzs1cu.us.auth0.com/samlp/metadata/sOKV7w0vVdq3ru3FoRKMDxiga8VSSJ7r
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
